apiVersion: v1
kind: Dev
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: k8s-deployment-demo
  replicas: 4 # tells deployment to run 4 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app:  k8s-deployment-demo
    spec:
      containers:
      - name:  k8s-deployment-demo
        image: sisco1206/dsg-httpd
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
